### ISSUE TITLE
live stream from youtube

### ISSUE THREAD

**Issue by Smart-Stadium** [abhiTronix/vidgear#133]
Hello, I'm trying to read live stream from youtube but after 10 seconds the streaming blocks.

I tried the following URL : https://www.youtube.com/watch?v=d29O7DT6NHQ - https://www.youtube.com/watch?v=1EiC9bvVGnk. 

I red your FAQ & Troubleshooting but I don't find a solution.

I'm working with the last version of Python (3.8 64 bits) and the version of Camgear on Windows 10.

Your code is very simple and works with simple youtube video and RSTP video without problem->
```python
# import libraries
from vidgear.gears import CamGear
import cv2
stream = CamGear(source='https://www.youtube.com/watch?v=d29O7DT6NHQ', y_tube =True).start() # YouTube Video URL as input
# infinite loop
while True:
    frame = stream.read()
    # read frames
    # check if frame is None
    if frame is None:
        #if True break the infinite loop
        break
    # do something with frame here
    cv2.imshow("Output Frame", frame)
    # Show output window
    key = cv2.waitKey(1) & 0xFF
    # check for 'q' key-press
    if key == ord("q"):
        #if 'q' key-pressed break out
        break
cv2.destroyAllWindows()
# close output window
stream.stop()
# safely close video stream.
```

**Comment by abhiTronix** [comment]
@Smart-Stadium This is a bug in OpenCV's FFmpeg backend which cannot handle hls/m3u8 streams provided by `youtube-dl` or `pafy`. Thereby, the real culprit here is FFmpeg which has following hls/m3u8 bug:

https://trac.ffmpeg.org/ticket/5348
https://trac.ffmpeg.org/ticket/6287
https://trac.ffmpeg.org/ticket/7804

### Steps to Reproduce Bug:
**First, Use youtube-dl to grab Youtube Video HLS m3u8 stream:**
```sh
youtube-dl -g "https://youtu.be/d29O7DT6NHQ"
```

**Then play that URL using FFmpeg's FFplay, it stops after few seconds:**
```sh
ffplay "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1591217239/ei/97fXXv3rA4mywgOv4brYCA/ip/103.206.248.130/id/d29O7DT6NHQ.906/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/r3---sn-bpb5oupj-qxae.googlevideo.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/initcwndbps/5040/mh/hQ/mm/44/mn/sn-bpb5oupj-qxae/ms/lva/mv/m/mvi/2/pl/24/dover/11/keepalive/yes/mt/1591195523/disable_polymer/true/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AOq0QJ8wRQIhAP_SCb7nBIMiIv3KvXim1H54wNHBFPVmCscvz4VieJp0AiBZX03sFC1cD3YYTBPnt2-sjxsZ_HnrFrG8s7XBg1tppQ%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgcc8v2_DuEfBByN_g0YiCfRxLmDEmMH2u04G7WM_rXGYCIQCFHnW8SjP2drb0nENv9SIeReNXOygJXbMvO6xYfBhtRA%3D%3D/playlist/index.m3u8"
```
 
**But if you play the same hls/m3u8 stream with [MPV media player](https://mpv.io/) using command:**
```sh
mpv "https://manifest.googlevideo.com/api/manifest/hls_playlist/expire/1591217239/ei/97fXXv3rA4mywgOv4brYCA/ip/103.206.248.130/id/d29O7DT6NHQ.906/itag/96/source/yt_live_broadcast/requiressl/yes/ratebypass/yes/live/1/goi/160/sgoap/gir%3Dyes%3Bitag%3D140/sgovp/gir%3Dyes%3Bitag%3D137/hls_chunk_host/r3---sn-bpb5oupj-qxae.googlevideo.com/playlist_duration/30/manifest_duration/30/vprv/1/playlist_type/DVR/initcwndbps/5040/mh/hQ/mm/44/mn/sn-bpb5oupj-qxae/ms/lva/mv/m/mvi/2/pl/24/dover/11/keepalive/yes/mt/1591195523/disable_polymer/true/sparams/expire,ei,ip,id,itag,source,requiressl,ratebypass,live,goi,sgoap,sgovp,playlist_duration,manifest_duration,vprv,playlist_type/sig/AOq0QJ8wRQIhAP_SCb7nBIMiIv3KvXim1H54wNHBFPVmCscvz4VieJp0AiBZX03sFC1cD3YYTBPnt2-sjxsZ_HnrFrG8s7XBg1tppQ%3D%3D/lsparams/hls_chunk_host,initcwndbps,mh,mm,mn,ms,mv,mvi,pl/lsig/AG3C_xAwRQIgcc8v2_DuEfBByN_g0YiCfRxLmDEmMH2u04G7WM_rXGYCIQCFHnW8SjP2drb0nENv9SIeReNXOygJXbMvO6xYfBhtRA%3D%3D/playlist/index.m3u8" 
```
**It plays just fine.**

**Comment by abhiTronix** [comment]
### Workaround for this Bug:

**Use different backend if available like Gstreamer:**

---
But first check your OpenCV to be built with GStreamer support. You can easily check it by running `print(cv2.getBuildInformation())` python command and see if output contains something similar as follows:
```sh
Video I/O:
 ...
     GStreamer:                   
       base:                      YES (ver 1.8.3)
       video:                     YES (ver 1.8.3)
       app:                       YES (ver 1.8.3)
...
```sh
---

Then, if Gstreamer support is present, then use this code:
```python
# import required libraries
from vidgear.gears import CamGear
import cv2

# Add YouTube Video URL as input source of your choice and change backend
stream = CamGear(source='https://youtu.be/d29O7DT6NHQ', y_tube=True, logging=True, backend=cv2.CAP_GSTREAMER).start() 

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break


    # {do something with the frame here}


    # Show output window
    cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()
# safely close video stream.
```

And problem is gone. Goodluck!

**Comment by imranilyas** [comment]
I tried the sample code provided above with a different url: https://www.youtube.com/watch?v=_fqpYLM6SCw&ab_channel=TheAIGuy

I have Gstreamer installed and the version(1.18.1) is displayed when I typed cv2.getBuildInformation()
This is the error I'm experiencing:

![image](https://user-images.githubusercontent.com/68575807/101452517-9f38db80-38e2-11eb-9209-fe8c32d82884.png)

**Comment by abhiTronix** [comment]
@imranilyas First of all, you don't need to enable **Gstreamer** backend for non-live streams. Being said that there's a bug in CamGear which recently got fixed in `testing` branch. Therefore, To eliminate this error, you can install the latest `testing` branch as follows:

**Remember on Windows OS:** _You'll also need to install Git for Windows (if you haven't already): https://gitforwindows.org/_

```sh
  # first update remember to  update `youtube-dl`
  python -m  pip install -U youtube-dl

  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout testing

  # OR install with asyncio support
 python -m  pip install .
```

Then you can rerun your example again and it should work. Good luck.

**Comment by imranilyas** [comment]
@abhiTronix I tried what you suggested and I am still experiencing the same error I was before when testing with a YouTube livestream. This only occurs when I have backend=cv2.CAP_GSTREAMER. When I remove it, the normal timed videos run fine. However, I need the livestreams which is why I need Gstreamer. Is there something I have to do with Gstreamer in order to get it piped in?

Livestream url: https://www.youtube.com/watch?v=my5iauCqerU&ab_channel=ComedyCentral

**Comment by abhiTronix** [comment]
@imranilyas What's the output of `python -c "import vidgear; print(vidgear.__version__)"` command?

**Comment by imranilyas** [comment]
Output is 0.1.9
When I check pip list, it says 0.2.0.dev2

**Comment by abhiTronix** [comment]
@imranilyas There are two `pip` package installation sites installed on your computer. How did you installed vidgear, and did you used `sudo`?

**Comment by imranilyas** [comment]
@abhiTronix I installed vidgear through pip install. I did not use sudo.

**Comment by abhiTronix** [comment]
> @abhiTronix I installed vidgear through pip install. I did not use sudo.
> In python37/Lib/site-packages/vidgear, the version.py file says 0.1.9 which is where I believe it's pulling the version number from.
> In python37/Lib/site-packages there is a vidgear folder and a vidgear-0.2.0.dev2.dist-info folder.
> 

@imranilyas Sorry, Yeah I was wrong, and unintentionally I gave you half instructions to solve this problem. **You need  to use `options={"FORCE_YTUBE_VAMODE":True}` flag for these special kind of YouTube videos _(that doesn't have 1080p video+audio streams) _, as follows:**

```python
# import required libraries
from vidgear.gears import CamGear
import cv2

# enable special mode
options={"FORCE_YTUBE_VAMODE":True}
# Add YouTube Video URL as input source of your choice and change backend
stream = CamGear(source='https://www.youtube.com/watch?v=_fqpYLM6SCw&ab_channel=TheAIGuy', y_tube=True, logging=True, backend=cv2.CAP_GSTREAMER, **options).start() 

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break


    # {do something with the frame here}


    # Show output window
    cv2.imshow("Output Frame", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()
```
**Try this code and this must solve your problem. Please report your result here too,**

**Comment by imranilyas** [comment]
@abhiTronix I tried the above solution with the same YouTube video link and this is the error I receive, the same error as before. When I remove `backend=cv2.CAP_GSTREAMER` and have a YouTube livestream as the source, I get these errors after the livestream runs for a couple of seconds.
[tls @ 000001d3aac4c880] Unable to read from socket
[tls @ 000001d3aac6d980] Failed to send close message
 

![image](https://user-images.githubusercontent.com/68575807/102128087-32ea3a80-3e02-11eb-928b-ee5c0ab156f7.png)

**Comment by abhiTronix** [comment]
> I tried the above solution with the same YouTube video link and this is the error I receive, the same error as before.

@imranilyas It is working all fine here, even tested on different machines. I can even record everything for your convenience if you like.


> When I remove backend=cv2.CAP_GSTREAMER and have a YouTube livestream as the source, I get these errors after the livestream runs for a couple of seconds.
> [tls @ 000001d3aac4c880] Unable to read from socket
> [tls @ 000001d3aac6d980] Failed to send close message

Yeah, that's why we are working on issue #160. You can wait for it as it will solve it.

**Comment by abhiTronix** [comment]
@imranilyas Can you do following and try again:
```sh
sudo add-apt-repository ppa:gstreamer-developers/ppa
sudo apt-get update
sudo apt-get install gstreamer1.0*
```

**Comment by imranilyas** [comment]
@abhiTronix Sorry for the late response. I'm using Git/Bash which neither supports sudo nor apt-get. I upgraded by downloading from the source for both gstreamer(1.18.2) and OpenCV(4.5.0) and compiled OpenCV using Visual Studio 2017. However, it still did not work.

Then, I tried using the command prompt and it WORKED! Thank you for all your help. I'm still not sure why it works on the Command Prompt but doesn't on Git/Bash, but it 100% worked. Thank you again! I really appreciate your quick responses.

**Comment by abhiTronix** [comment]
This issue cannot be resolved at this moment as vidgear as we need to [**patch FFmpeg itself**](https://github.com/zaps166/QMPlay2/issues/139) first to progress further, thereby need we'll work on this after #148 is done. The required patch can be found here: http://git.videolan.org/?p=ffmpeg.git;a=commitdiff;h=a606f27f4c610708fa96e35eed7b7537d3d8f712

**Comment by abhiTronix** [comment]
**Temporarily Resolved in commit https://github.com/abhiTronix/vidgear/commit/bf1b8aabd0a21543570457e8aeb7775339611b18 and now no need to specify GStreamer backend(`cv2.CAP_GSTREAMER`) manually, CamGear automatically enforces it.**

**Comment by abhiTronix** [comment]
@Smart-Stadium I think #274 resolves this issue too. 

Clone and Install `development` branch:

```sh
  # clone the repository and get inside
  git clone https://github.com/abhiTronix/vidgear.git && cd vidgear

  # checkout the latest testing branch
  git checkout development

  # install normally
  pip install .[core]

  # OR install with asyncio support
  pip install .[asyncio]
```
Test your code:
```python
# import required libraries
from vidgear.gears import CamGear
import cv2

options = {"STREAM_RESOLUTION": "720p"}

# Add YouTube Video URL as input source (for e.g https://youtu.be/bvetuLwJIkA)
# and enable Stream Mode (`stream_mode = True`)
stream = CamGear(
    source="https://youtu.be/j1GLs_fMn1s", stream_mode=True, logging=True, **options
).start()

# loop over
while True:

    # read frames from stream
    frame = stream.read()

    # check for frame if Nonetype
    if frame is None:
        break

    # {do something with the frame here}

    # Show output window
    cv2.imshow("Output", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()

# safely close video stream
stream.stop()
```

**Comment by abhiTronix** [comment]
**Successfully resolved and merged in commit: https://github.com/abhiTronix/vidgear/commit/dc26c00bcb4ec6e40645b4ad1aa1aedf4f0c6b43**

### Usage docs are available at: https://abhitronix.github.io/vidgear/v0.2.4-dev/gears/camgear/usage/#using-camgear-with-youtube-videos

**Comment by Smart-Stadium** [comment]
Thank you for your job. My project is finished but as soon as I have a little bit time, I'll test.

**Comment by Teagueporter** [comment]
I'm getting a Invalid NAL unit 0, skipping error. I have
 stream = CamGear(
    source="https://youtu.be/j1GLs_fMn1s", stream_mode=True, logging=True, **options
).start()

and sometimes the video will play for a couple seconds and then freeze and it won't play any more. The goal is I'm trying to get a live stream from youtube using openCV and then apply some background segmentation.

**Comment by Teagueporter** [comment]
@abhiTronix ok sounds good! Thank you! Do you know how long it might take?

**Comment by abhiTronix** [comment]
> @abhiTronix ok sounds good! Thank you! Do you know how long it might take?

That might take a while. But you can use Deffcode right now as follows with CamGear, it's pretty simply actually:

```python
# import required libraries
from vidgear.gears import CamGear
# import the necessary packages
from deffcode import FFdecoder


# Add YouTube Video URL as input source (for e.g https://youtu.be/uCy5OuSQnyA)
# and enable Stream Mode (`stream_mode = True`)
stream = CamGear(
    source="https://youtu.be/j1GLs_fMn1s", stream_mode=True, logging=True
).start()

# get Video's metadata as JSON object
video_metadata =  stream.ytv_metadata

# get data like `url`
source_url = video_metadata["url"]

# close CamGear
stream.stop()

# initialize and formulate the decoder for BGR24 output
decoder = FFdecoder(source_url, frame_format="bgr24").formulate()

# grab the BGR24  frame from the decoder
for frame in decoder.generateFrame():

    # check if frame is None
    if frame is None:
        break

    # Do here whatever you want

    # Show output window
    cv2.imshow("Output", frame)

    # check for 'q' key if pressed
    key = cv2.waitKey(1) & 0xFF
    if key == ord("q"):
        break

# close output window
cv2.destroyAllWindows()
# terminate the decoder
decoder.terminate()
```

Make sure you install deffcode and FFmpeg correctly on your machine. You can find related docs here: https://abhitronix.github.io/deffcode/latest/installation/

**Comment by abhiTronix** [comment]
@Teagueporter This code will work for the time being. Please report any issues if found. Goodluck.

**Comment by Teagueporter** [comment]
Thank you!

**Comment by Teagueporter** [comment]
@abhiTronix Sorry for so many questions but does GStreamer have to be working? I have deffcode and CamGear and i'm using the same layout as the code you posted above but I'm still getting an Invalid Nal unit 0 after 3ish seconds

**Comment by abhiTronix** [comment]
@Teagueporter I'm not seeing any deffcode logs except version. Paste the complete logs with `verbose=True` in FFdecoder.

**Comment by Teagueporter** [comment]
@abhiTronix Sorry I get the error in my terminal, here is the screen shot of that error
![Screenshot from 2022-05-25 10-59-13](https://user-images.githubusercontent.com/37876539/170319484-65c03091-02a0-4b77-a07f-2c9e0c3cb12b.png)
.
What happens is the video will play for about 4 to 5 seconds but the invail nal unit error will happen almost as soon as I begin the program
